openapi: "3.0.1"
info:
  title: "unicom"
  version: "2025-03-14 14:25:22UTC"
servers:
- url: "https://vnj3ipea30.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: ""
paths:
  /posts/{id}:
    get:
      responses:
        default:
          description: "Default response for GET /posts/{id}"
    delete:
      responses:
        default:
          description: "Default response for DELETE /posts/{id}"
    patch:
      responses:
        default:
          description: "Default response for PATCH /posts/{id}"
    parameters:
    - name: "id"
      in: "path"
      description: "Generated path parameter for id"
      required: true
      schema:
        type: "string"
  /users/{id}:
    get:
      responses:
        default:
          description: "Default response for GET /users/{id}"
    delete:
      responses:
        default:
          description: "Default response for DELETE /users/{id}"
    patch:
      responses:
        default:
          description: "Default response for PATCH /users/{id}"
    parameters:
    - name: "id"
      in: "path"
      description: "Generated path parameter for id"
      required: true
      schema:
        type: "string"
  /myposts:
    get:
      responses:
        default:
          description: "Default response for GET /myposts"
  /posts:
    get:
      responses:
        default:
          description: "Default response for GET /posts"
    post:
      responses:
        default:
          description: "Default response for POST /posts"
  /signedurl:
    get:
      responses:
        default:
          description: "Default response for GET /signedurl"
x-amazon-apigateway-importexport-version: "1.0"